# Generated by Django 5.0.6 on 2025-01-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_review_owner_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-vote_ratio", "-vote_total", "title")},
        ),
    ]
